# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lib/proto/sentence.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("lib/proto/sentence.proto", :syntax => :proto3) do
    add_message "Sentences" do
      repeated :sentence, :message, 1, "Sentence"
    end
    add_message "Sentence" do
      optional :no, :int64, 1
      optional :score, :int64, 2
    end
    add_message "User" do
      optional :id, :string, 1
    end
  end
end

Sentences = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Sentences").msgclass
Sentence = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Sentence").msgclass
User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("User").msgclass
