# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lib/proto/sentence.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("lib/proto/sentence.proto", :syntax => :proto3) do
    add_message "Sentence" do
      optional :no, :int64, 1
    end
    add_message "User" do
      optional :id, :string, 1
    end
  end
end

Sentence = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Sentence").msgclass
User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("User").msgclass
